apiVersion: batch/v1
kind: Job
metadata:
  name: job-0
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: NAME
          image: IMAGE
          envFrom:
            - secretRef:
                name: secrets
          env:
            - name: START_DATE
              value: "2022/07/17"
            - name: END_DATE
              value: "2022/07/18"
          resources:
            limits:
              memory: 5Gi
              cpu: 2
            requests:
              memory: 5Gi
              cpu: 2
      restartPolicy: Never
  backoffLimit: 2
  
