apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-app
  name: my-app
  namespace: my-namespace
spec:
  type: LoadBalancer
  ports:
  - name: "my-app-service"
    port: 8080
    targetPort: 8080
  selector:
    app: my-app
