apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-api
  name: my-api
  namespace: my-namespace
spec:
  type: ClusterIP
  ports:
  - name: "my-api-service"
    port: 8888
    targetPort: 8888
  selector:
    app: my-api
